name: orfanos
favicon: null
layout_spectrum: 0.9189811209216714
typography_spectrum: 0.2241199433337897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8810419731307775
  lightness: 0.9824576252140105
  saturation: 0.8590114987455308
  rhythmicContrast: 0.19874900113791227
purpose: []
